### ISSUE TITLE
Error glog /bin/bash^M: bad interpreter

### ISSUE THREAD

**Issue by hugo-chavar** [sfernandez11/SisProH#1]
Al correr un log en linux

```
>glog.sh Prueba errorX
```

Obtengo

```
-bash: /users/c8544479/bin/glog.sh: /bin/bash^M: bad interpreter: No such file or directory
```

**Comment by mmanz** [comment]
La linea #!/bin/bash es necesaria para indicar en que está escrito el
script, por lo tanto como debe interpretarse, no se debería sacar.

El error parecería ser porque el archivo está medio corrupto y tiene un ^M
agregado al final.

**Comment by sfernandez11** [comment]
Solucionado

**Comment by hugo-chavar** [comment]
Me sigue dando el mismo error. Vos estas programando en windows? o tal vez git cambia algo.. porque el problema son los line ending CRLF en linux espera q sean LF
Yo hice esto para arreglarlo si otro tiene el mismo problema:

```
mv glog.sh glog_old.sh

cat glog_old.sh | sed '/\015/d' >glog.sh

vi glog.sh
:set ff=unix
```

**Comment by sfernandez11** [comment]
Que raro que siga apareciendo ese error. Yo estoy usando linux para
programar y no Windows, tal vez tengas razón y sea git el que cambia algo
aunque sería raro también eso.
Voy a intentar borrar el archivo de git y volverlo a subir a ver que pasa.

**Comment by hugo-chavar** [comment]
Listo, subi una configuracion que lo soluciona

**Comment by agscontini** [comment]
yo pregunto...de dónde saca los parametros de $CONFDIR Y $LOGDIR porque cuando busco correrlo desde un scrip pedorro, pasandole los parametros me intenta generar el archivo /ProPro.log pero eso es en el directorio principal, y no va a tener permisos nunca....en $LOGDIR no reconoce nada, y no debería ser una variable del ambiente porque esas se generan en otro proceso y el instalador ya tiene que poder loguear. 
 mi script bien simple lo corri en ProPro y es el ProPro.sh y hace esto:
. ProPro.sh
../glog.sh: línea 60: /ProPro.log: Permiso denegado
stat: no se puede efectuar `stat' sobre «/ProPro.log»: No existe el archivo o el directorio
tail: no se puede abrir «/ProPro.log» para lectura: No existe el archivo o el directorio
rm: no se puede borrar «/ProPro.log»: No existe el archivo o el directorio
mv: no se puede mover «templog.log» a «/ProPro.log»: Permiso denegado
teto.test

**Comment by hugo-chavar** [comment]
cuando testeas tenes que forzar esas variables, ya que solo van a existir
cuando se corra el InsPro.
Para forzar, antes de probar el log haces esto:
export CONFDIR=/eldirectorio que quieras   --> te recomiendo $PWD
lo mismo con las demás

**Comment by sfernandez11** [comment]
Claro, yo lo pensé que cuando se quiera usar el glog si es en el InsPro el
mismo instalador va a exportar las variables que necesite para usarlo,
LOGDIR no la necesita sólo necesita CONFDIR,  y sigue instalando y después
ya en el IniPro ahí ya inicia todas las variables del ambiente y va a
funcionar para todos los demás procesos que usen al glog.

**Comment by agscontini** [comment]
ahi me funciona bien generandole la variable logdir y exportandola. 
No deberíamos hacerle un archivo de configuración mínimo de donde levantamos esas cosas mínimas para el log?
 Me tiro esto que viene por el mismo lado.
../glog.sh: 65: [: -gt: argument expected 
calculo que el logsize también debería haberlo seteado o que vendría seteado de otro lado.
 Gracias.

**Comment by hugo-chavar** [comment]
estamos en eso agustin... por el momento haganlo a mano por favor, esa parte de asignacion de variables corresponde al IniPro

**Comment by mmanz** [comment]
Me tocaba a mi esa parte, mañana tengo que entregar una parte de un tp y tengo otro la otra semana por eso no toque mucho de este, si alguien quiere hacerlo se lo cambio por otra cosa que no sea tan dependiente, si no metanlo a mano por ahora, voy a ver si puedo armar algo rápido.

**Comment by recheconea** [comment]
No te hagas problema, la podemos pilotear sin mucho problema por ahora.

**Comment by agscontini** [comment]
Acuerdo. Por ahora dudo que sea un problema.
