### ISSUE TITLE
Error glog syntax error near unexpected token `elif'

### ISSUE THREAD

**Issue by hugo-chavar** [sfernandez11/SisProH#2]
Al correr un log en linux

```
>glog.sh Prueba errorX
```

Obtengo

```
: command not found
: command not found
: command not found
: command not found
./glog.sh: line 21: syntax error near unexpected token `elif'
./glog.sh: line 21: `elif [ $# -eq 2 ]  # Si hay 2 parametros se toma la variabl' WHAT = INFO por default.
```

Sugiero ver esto:
http://stackoverflow.com/questions/4182122/syntax-error-near-unexpected-token-elif

**Comment by sfernandez11** [comment]
Solucionado, los dos problemas es porque el archivo .sh se habia dañado, lo volvi a hacer en otro archivo y ahora ya funciona.
Para probar el log, primero hay que asegurarse que el script tenga permisos de ejecucion y despues
./glog "Donde" "Mensaje de error" "INFO/WAR/ERR" puede ir con o sin comillas.
Lo que si van a notar que no aparece el mensaje por pantalla, eso es porque esta redirigido a la variable LOGPATH, si lo sacan se puede probar para que aparezca por pantalla.
