### ISSUE TITLE
Log excedido

### ISSUE THREAD

**Issue by mmanz** [sfernandez11/SisProH#8]
Siempre me aparece "Log exedido" varias veces al principio del archivo, a alguien más le pasa? 

Por ejemplo:

Log Excedido.
 Log Excedido.
 Log Excedido.
 Log Excedido.
dom may  3 14:49:16 ART 2015-mery-IniPro-INFO-Se agrego /home/mery/Dropbox/fiuba/7508_Sistemas_Operativos/tp/SisProH/grupo02/bin al PATH. PATH= /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/mery/.rvm/bin:/home/mery/Dropbox/fiuba/7508_Sistemas_Operativos/tp/SisProH/grupo02/bin
dom may  3 14:49:16 ART 2015-mery-IniPro-INFO-Estado del Sistema: INICIALIZADO
dom may  3 14:50:15 ART 2015-mery-IniPro-INFO-Iniciando el demonio RecPro
dom may  3 14:50:15 ART 2015-mery-IniPro-WAR-El demonio ya se encuentra inicializado, no se realizó ninguna acción
dom may  3 14:50:15 ART 2015-mery-IniPro-INFO-Fin de ejecucion del IniPro

**Comment by sfernandez11** [comment]
Hola, eso puede ser por el valor que se le asigna a la variable LOGSIZE,
porque el log se fija si el tamaño del archivo es mas grande que esa
variable y si eso pasa agarra las ultimas 50 lineas del archivo y agrega en
un nuevo log. Entonces si la variable es muy chica y no hay muchas lineas
escritas se debe escribir varias veces Log Excedido, va al menos llegue a
esa conclusion revisando el codigo de glog.sh

**Comment by mmanz** [comment]
Me pareció raro porque "Estado del sistema: INICIALIZADO" es lo primero que
loguea el IniPro (o sea, antes de eso no existe, por lo que no tiene
nada...)

Podríamos aumentar el valor máximo del log por default si es eso, la verdad
que no logueo mucho como para que se exceda, tendrá como muuucho dos
pantallas de largo.

2015-05-03 15:17 GMT-03:00 Santiago Fernandez notifications@github.com:

> Hola, eso puede ser por el valor que se le asigna a la variable LOGSIZE,
> porque el log se fija si el tamaño del archivo es mas grande que esa
> variable y si eso pasa agarra las ultimas 50 lineas del archivo y agrega en
> un nuevo log. Entonces si la variable es muy chica y no hay muchas lineas
> escritas se debe escribir varias veces Log Excedido, va al menos llegue a
> esa conclusion revisando el codigo de glog.sh
>

**Comment by hugo-chavar** [comment]
A mi tambien me pasa. El valor default de LOGSIZE es 400kb pero eso aparece cuando el log esta en 2 kb.. es raro

**Comment by hugo-chavar** [comment]
no estaras tomando 400 bytes en lugar de Kb ?

**Comment by sfernandez11** [comment]
Es lo que iba a decir justo. La variable tamaño con la cual comparó logsize
esta en bytes porque es lo que me devuelve la función stat. Ahora, la
variable logsize esta en bytes o en kb? Tal vez puede venir por ahí el
problema.

**Comment by hugo-chavar** [comment]
LOGSIZE es en Kb

**Comment by hugo-chavar** [comment]
fijate como paso los bytes a kb con estas funciones:

```
function divide(){
  echo $((($1 + $2/2) / $2))
}

function freeSpace(){
  local free_space_bytes
  free_space_bytes=`df $1 | tail -n 1 | tr -s ' ' | cut -d' ' -f 4`

  echo $(divide $free_space_bytes 1024)
}
```

**Comment by sfernandez11** [comment]
Ah entonces era por eso lo que pasaba. Ahora lo modifico en el glog.sh y lo
subo.

2015-05-03 15:36 GMT-03:00 hugo-chavar notifications@github.com:

**Comment by sfernandez11** [comment]
Arreglado y subido.

2015-05-03 15:39 GMT-03:00 Santiago Fernandez fernandezsantid@gmail.com:
